[package]
name = "v0latil3"
version = "0.1.0"
edition = "2021"
authors = [
  "Gilbert Kiana",
  "Brian M'Ikiara"
]

[dependencies]
hyper_wasi = { version = "0.15.2", features = ["full"] }
tokio_wasi = { version = "1.25", features = ["full"] }
crossterm = "0.27.0"